### ISSUE TITLE
Any plans for supporting multi dimensional RNN?  

### ISSUE THREAD

**Issue by shampool** [lmjohns3/theanets#105]
http://people.idsia.ch/~juergen/icann_2007.pdf

**Comment by lmjohns3** [comment]
No plans to implement this. You can always manually configure your input and output data so that they are serialized into a 1D sequence, which theanets will handle using the standard recurrent configuration without changes.

If you get around to implementing a layer and corresponding model for this, I'd be happy to take a PR.
